---
fixtures:
  repositories:
    concat:
      # master is beyond 4.1.1, but has breaking changes to
      # how fragments are ordered (MODULES-6625)
      repo: https://github.com/simp/puppetlabs-concat
      ref: 4.1.1
    iptables:  https://github.com/simp/pupmod-simp-iptables
    logrotate: https://github.com/simp/pupmod-simp-logrotate
    pki:       https://github.com/simp/pupmod-simp-pki
    rsync:     https://github.com/simp/pupmod-simp-rsync
    rsyslog:   https://github.com/simp/pupmod-simp-rsyslog
    simplib:   https://github.com/simp/pupmod-simp-simplib
    snmp:
      repo:  https://github.com/simp/puppet-snmp
      ref:   3.9.0
    stdlib:  https://github.com/simp/puppetlabs-stdlib
    systemd:
      repo: https://github.com/simp/puppet-systemd
      branch: simp-master
    tcpwrappers: https://github.com/simp/pupmod-simp-tcpwrappers
  symlinks:
    simp_snmpd: "#{source_dir}"
