# This nodeset spins up a simple one-host test VM for both EL6 and EL7
HOSTS:
  centos-7-1:
    roles:
      - defaultparams
      - el7
      - default
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: vagrant
  centos-6-1:
    roles:
      - defaultparams
      - el6
    platform:   el-6-x86_64
    box:        centos/6
    hypervisor: vagrant
  centos-7-2:
    roles:
      - customparams
      - el7
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: vagrant
  centos-6-2:
    roles:
      - customparams
      - el6
    platform:   el-6-x86_64
    box:        centos/6
    hypervisor: vagrant
CONFIG:
  log_level: verbose
  type:      aio
  vagrant_memsize: 256
  ## vb_gui: true
